-- 코드를 입력하세요
SELECT DISTINCT(R.CAR_ID) AS CAR_ID FROM CAR_RENTAL_COMPANY_CAR R
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON R.CAR_ID = H.CAR_ID
WHERE R.CAR_TYPE LIKE '세단'
AND H.START_DATE LIKE '2022-10%'
ORDER BY CAR_ID DESC